version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_GCS_BUCKET_URL=${NEXT_PUBLIC_GCS_BUCKET_URL}
        - NEXT_PUBLIC_GCS_BUCKET_PUBLIC_URL=${NEXT_PUBLIC_GCS_BUCKET_PUBLIC_URL}
        - NEXT_PUBLIC_ENV_STATUS=${NEXT_PUBLIC_ENV_STATUS}
        - NEXT_PUBLIC_MESHMELL_GITHUB_REPOSITORY=${NEXT_PUBLIC_MESHMELL_GITHUB_REPOSITORY}
        - NEXT_PUBLIC_NUM_OF_MODEL_BY_PAGE=${NEXT_PUBLIC_NUM_OF_MODEL_BY_PAGE}
        - FIREBASE_ADMIN_PROJECT_ID=${FIREBASE_ADMIN_PROJECT_ID}
        - FIREBASE_ADMIN_CLIENT_EMAIL=${FIREBASE_ADMIN_CLIENT_EMAIL}
        - FIREBASE_ADMIN_DATABASE_URL=${FIREBASE_ADMIN_DATABASE_URL}
        - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
        - GCS_TYPE=${GCS_TYPE}
        - GCS_CLIENT_ID=${GCS_CLIENT_ID}
        - GCS_PROJECT_ID=${GCS_PROJECT_ID}
        - GCS_CLIENT_EMAIL=${GCS_CLIENT_EMAIL}
        - FIREBASE_ADMIN_PRIVATE_KEY=${FIREBASE_ADMIN_PRIVATE_KEY}
        - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
    ports:
      - '3000:3000'
    env_file:
      - .env
